### PR TITLE
add model: gpt-4-dalle (generate image) 

### PR DESCRIPTION
**Pull request by wjs7740**
add gpt-4-dalle to generate images, like this
dalle-logo

### CODE REVIEW

**Comment by c121914yu** [comment]
这个模型似乎没看到官方介绍？

**Comment by leoterry-ulrica** [comment]
你这个压根不是什么增强功能，你的修改都可以通过外部配置文件进行修改。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
This is not an enhancement at all. Your modifications can be made through external configuration files.

**Comment by wjs7740** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> This is not an enhancement at all. Your modifications can be made through external configuration files.

是我弄错了，还需要oneapi对官方接口转换一下，我关闭掉这个PR

**Pull request closed without merging**
