### PR TITLE
知识库搜索测试接口增加预估长度修改 /api/core/dataset/searchTest

### PR DESCRIPTION
**Pull request by jiumengs**

### CODE REVIEW

**Comment by c121914yu** [comment]
# 🤖 Generated by deploy action
[👀 Visit Preview](https://fastgpt-staging.vercel.app)

**Comment by c121914yu** [comment]
不打算修改这个，容易炸库。

**Comment by jiumengs** [comment]
800字对于某一些小段落回答太多了，会有不必要的返回。

**Comment by c121914yu** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
800 words is too much to answer certain small paragraphs, and there will be unnecessary returns.

**Pull request closed without merging**
